#ifndef __PGTABLE_2LEVEL_DEFS_H__
#define __PGTABLE_2LEVEL_DEFS_H__

#define PGDIR_SHIFT 22
#define PTRS_PER_PGD 1024
#define PTRS_PER_PTE 1024

#define PTRS_PER_PMD 1

#endif // __PGTABLE_2LEVEL_DEFS_H__
